project1/app1/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.hello),
    path('bemvindo', views.bemvindo),
]

project1/contactos/urls.py
from django.urls import path
from . import views

app_name = 'contactos'

urlpatterns = [
    path('', views.home, name = 'home'),
    path('add/', views.add, name='add'),
    path('delete/<int:id>', views.delete, name = 'delete'),
    path('edit/<int:id>', views.edit, name = 'edit'),
]

project1/lista_compras/urls.py
from django.urls import path
from . import views

app_name = 'lista_compras'

urlpatterns = [
    path('', views.home, name = 'home'),
    path('adicionar/', views.add, name= 'add'),
    path('eliminar/<int:id>', views.delete, name = 'delete'),
]

project1/mostrar_api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name = 'home'),
]

project1/project1/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('todo/', include('toDo.urls')),
    path('app1/', include('app1.urls')),
    path('admin/', admin.site.urls),
    path('lista_compras/', include('lista_compras.urls')),
    path('contactos/', include('contactos.urls')),
    path('mostrar_api', include('mostrar_api.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project1/toDo/urls.py
from django.urls import path
from . import views

app_name = 'toDo'

urlpatterns = [
    path('', views.mostrar_tarefas, name ='home'),
    path('adicionar/', views.inserir_tarefa, name = 'inserir'),
    path('eliminar/<int:id>', views.eliminar_tarefa, name = 'eliminar'),
    path('alterar/<int:id>', views.alterar_tarefa , name = 'alterar'),
]

project1/contactos/models.py
from django.db import models

# Create your models here.
class Categoria(models.Model):
    categoria = models.CharField(max_length = 100, unique = True)

    def __str__(self) -> str:
        return self.categoria
    
    class Meta:
        ordering = ['categoria']

class Contacto(models.Model):
    nome = models.CharField(max_length = 225)
    telemovel = models.CharField(max_length = 20)
    email = models.EmailField(blank = True, null = True)
    telemovel2 = models.CharField(max_length = 20, blank = True, null = True)
    favorito = models.BooleanField(default = False)
    
    # py -m pip install Pillow para usar ImageField
    foto = models.ImageField(upload_to = 'contactos/fotos/', blank = True, null = True)
    categoria = models.ForeignKey(Categoria, on_delete = models.SET_NULL, blank = True, null = True)

    def __str__(self) -> str:
        return self.nome

    class Meta:
        ordering = ['nome']

project1/lista_compras/models.py
from django.db import models

# Create your models here.
class Artigo(models.Model):

    OPCOES = [
        ('U', 'Urgente'),
        ('N', 'Não Urgente')
    ]

    nome = models.CharField(max_length = 252)
    # blank = True -> campo de preenchimento no formulário pode ficar vazio
    quantidade = models.CharField(max_length = 20, default = '1', blank = True)
    urgente = models.CharField(max_length = 1, choices = OPCOES, default = 'N')

    def __str__(self) -> str:
        return self.nome + " - " + self.quantidade

project1/mostrar_api/models.py
from django.db import models

# Create your models here.

project1/toDo/models.py
from django.db import models

# Create your models here.
class Tarefa(models.Model):
    nome = models.CharField(max_length = 255)
    concluido = models.BooleanField(default = False)
    data = models.DateTimeField(auto_now_add = True)

    def __str__(self) -> str:
        return self.nome
    

project1/contactos/forms.py
from django import forms
from contactos.models import Contacto
 
class ContactoForm(forms.ModelForm):
    class Meta:
        model = Contacto
        fields = "__all__"

project1/lista_compras/forms.py
from django import forms

from lista_compras.models import Artigo


class ArtigoForm(forms.ModelForm):
    class Meta:
        model = Artigo
        fields = "__all__"

project1/toDo/forms.py
from django import forms
from toDo.models import Tarefa

class TarefaForm(forms.ModelForm):
    class Meta: 
        model = Tarefa
        fields = "__all__"
        #fields = ('nome',)   # se for só um campo... tem que ser ('campo1',)
        #fields = ('nome','concluido')

project1/app1/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def hello(request):
    return HttpResponse("<h1>Olá</h1>")

def bemvindo(request):
    return render(request, "bem-vindo.html", {'nome':'Carlos'})

project1/contactos/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from contactos.models import Contacto
from contactos.forms import ContactoForm

# Create your views here.

def home(request):
    contactos = Contacto.objects.all()
    return render(request, 'contactos/home.html', {'contactos':contactos})


def add(request):
    formulario = ContactoForm()
    if request.method == "POST":
        # request files permite o upload de imagens
        formulario = ContactoForm(request.POST, request.FILES)
        if formulario.is_valid():
            formulario.save()
            return redirect('contactos:home')
    return render(request,'contactos/add.html', {'formulario':formulario})

def delete(reqeust, id):
    contacto = Contacto.objects.filter(pk = id)
    contacto.delete()
    return redirect('contactos:home')

def edit(request, id):
    try:
        contacto = Contacto.objects.get(pk = id)
    except:
        return HttpResponse("Erro: o contacto não existe.")
        # em html redirediona para pagina no tempo definido <meta http-equiv="refresh" content="5; URL={% url 'contactos:home' %}"/>
       
    else:
        # Cria formulario com a informação antiga do contacto
        formulario = ContactoForm(instance = contacto)
        if request.method == 'POST':
            # tem que referir a instancia do formualario (registo) para não inserir um novo
            formulario = ContactoForm(request.POST, request.FILES, instance = contacto)
            formulario.save()
            return redirect('contactos:home')
        return render(request, 'contactos/edit.html', {'formulario':formulario})

project1/lista_compras/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from lista_compras.models import Artigo
from lista_compras.forms import ArtigoForm


# Create your views here.
def home(request):

    # obter dados do Modelo
    artigos = Artigo.objects.all()
    
    return render(request, 'lista_compras/home.html', {'artigos':artigos})

def add(request):
    formulario = ArtigoForm()
    if request.method == "POST":
        formulario = ArtigoForm(request.POST)
        formulario.save()
        return redirect('lista_compras:home')
    return render(request, 'lista_compras/add.html', {'formulario':formulario})


def delete(request, id):
    try:
        artigo1 = Artigo.objects.get(pk = id)
        artigo1.delete()
    except:
        return HttpResponse("<p>Ocorreu um erro. Artigo não encontrado.<\p>")
    else:
        return redirect('lista_compras:home')

project1/mostrar_api/views.py
from django.shortcuts import render
import requests

# Create your views here.
def home(request):
    response = requests.get('https://catfact.ninja/fact')
    cat_info = response.json()
    return render(request, 'mostrar_api/home.html', {'dados': cat_info})

project1/toDo/views.py
from django.shortcuts import redirect, render
from toDo.models import Tarefa
from toDo.forms import TarefaForm

# Create your views here.
def mostrar_tarefas(request):
    tarefas= Tarefa.objects.all().filter(concluido = False).order_by('data')
    numero = len(tarefas)
    return render(request, 'toDo\home.html', {'tarefas': tarefas, 'numero': numero})

def inserir_tarefa(request):
    # criar formulário
    formulario = TarefaForm()
    if request.method == "POST":
        formulario = TarefaForm(request.POST)
        formulario.save()
        return redirect('toDo:home')
    return render(request, 'toDo/adicionar.html', {'formulario': formulario})
    

def eliminar_tarefa(request, id):
    # eliminar tarefa com id
    tarefa1 = Tarefa.objects.get(pk = id)
    tarefa1.delete()
    #redirecionar para a página home
    return redirect('toDo:home')


def alterar_tarefa(request,id):
    #obter a informação antiga daquela tarefa
    tarefa1 = Tarefa.objects.get(pk=id)
    if request.method == 'GET':
            formulario = TarefaForm(instance=tarefa1)
            return render(request,'toDo/alterar.html', {'formulario':formulario})
    elif request.method == 'POST':
        formulario = TarefaForm(request.POST, instance=tarefa1)
        #update
        formulario.save()
        return redirect('toDo:home')

project1/app1/templates/bem-vindo.html
<!DOCTYPE html>
<html lang="pt-pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>App1</title>
</head>
<body>
    <!--MVT - Model Viwe Template
    duplas chavetas para imprimir valor da variável
    chaveta e percentagem para introduzir cod py no meio-->

    {% if nome %}
    <h1>Bem-vindo(a) {{nome}}!</h1> 
    {% else %}
    <h1>Bem-vindo!</h1>
    <!-- não usa indantação, precisamos definir quando acaba o if-->
    {% endif %}
</body>
</html>

project1/contactos/templates/contactos/add.html
{%extends 'contactos/base.html' %}
<!DOCTYPE html>
<html lang="pt-pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>App - Contactos</title>
</head>
<body>
    {% block conteudo %}
    <h2>Adicionar contacto</h2>

    <form method="POST" enctype="multipart/form-data">
 
        {% csrf_token %}
       
        {{ formulario.as_p }}
       
        <p><button>Adicionar</button></p>
    </form>
    {% endblock %}
</body>
</html>

project1/contactos/templates/contactos/base.html
<!DOCTYPE html>
<html lang="pt-pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestão de COntactos</title>
</head>
<body>
    <header>
        <h1>App Gestão de Contatcos</h1>
    </header>
    <hr>
    <main>
        {% block conteudo %}

        {% endblock %}
    </main>
</body>
</html>

project1/contactos/templates/contactos/edit.html
{%extends 'contactos/base.html' %}
<!DOCTYPE html>
<html lang="pt-pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>App Contacto - Editar</title>
</head>
<body>
   {% block conteudo %}
    <h2>Editar contacto</h2>
    <form method="POST" enctype="multipart/form-data">
 
        {% csrf_token %}
       
        {{ formulario.as_p }}
       
        <p><button>Guardar alterações</button></p>
    </form>
    {% endblock %}
</body>
</html>

project1/contactos/templates/contactos/home.html
{%extends 'contactos/base.html' %}
<!DOCTYPE html>
<html lang="pt-pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contactos</title>
</head>
<body>
    <main>
    {% block conteudo %}
        <h2>Lista de Contactos</h2>
        <a href="{% url 'contactos:add' %}">Adicionar contacto<img src="../../../static/add.svg" alt=""></a>

        {% for contacto in contactos %}
        <div>
            <p>
                {% if contacto.foto %}
                <img src="{{contacto.foto.url}}" width="50">
                {% endif %}
                <a href="{% url 'contactos:delete' contacto.id %}"><img src="../../../static/trash3.svg" alt="caixote do lixo"></a>
                <a href="{% url 'contactos:edit' contacto.id %}"><img src="../../../static/pencil-fill.svg" alt="lápis - editar"></a><br>
                {{contacto.nome}} - {{contacto.telemovel}} | {{contacto.email}}<br>
                {% if contacto.telemovel2 %}
                    Tlm alternativo: {{contacto.telemovel2}}
                {% endif %}
            </p>
        </div>
        {% endfor %}

    {% endblock %}
</main>
</body>
</html>

project1/lista_compras/templates/lista_compras/add.html
<!DOCTYPE html>
<html lang="pt-pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>App 3</title>
</head>
<body>
    <h1>Adicionar artigo</h1>
    <form method = "POST">
        {% csrf_token %}

        <!-- mostra o formulário separado por parágrafos-->
        {{formulario.as_p}}
         <p><button type="submit">Adicionar</button></p>
    </form>
   
</body>
</html>

project1/lista_compras/templates/lista_compras/home.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>App3</title>
</head>
<body>
    <h1>Lista de Compras</h1>
    <ul>
        {% for artigo in artigos %}

        <li>{{artigo}} <a href="{% url 'lista_compras:delete' artigo.id %}"><img src="{% static 'trash3.svg' %}" alt="caixote do lico - eliminar"></a></li>
    
        {% endfor %}
    </ul>
   
    <a href="{% url 'lista_compras:add' %}">Adicionar artigo 
        <img src="{% static 'add.svg' %}" alt="mais - adicionar">
    </a>
</body>
</html>

project1/mostrar_api/templates/mostrar_api/home.html
<!DOCTYPE html>
<html lang="pt-pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>API</title>
</head>
<body>
    <h1>Mostrar dados de uma API em JSON</h1>
    <h2>https://catfact.ninja/fact</h2>

    {{dados.fact}}
</body>
</html>

project1/toDo/templates/toDo/adicionar.html
<h1>Nova tarefa</h1>

<form method="post">
    {% csrf_token %}

    {{ formulario.as_p }}

    <p><button>Adicionar</button></p>
</form>

project1/toDo/templates/toDo/alterar.html
<h1>Alterar tarefa</h1>
 
<form method="post">
 
    {% csrf_token %}
 
    {{ formulario.as_p }}
 
    <p><button>alterar</button></p>
</form>

project1/toDo/templates/toDo/home.html
<!DOCTYPE html>
<html lang="pt-pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>To Do App</title>
</head>
<body>
  {% load static %}
  <h1>Lista de Tarefas</h1>
 
<p>{{ numero }} tarefa(s) por realizar! </p>
 
<ul>
    {% for x in tarefas %}
 
    <li>{{x.id}} - {{ x.nome }}
        <a href="{% url 'toDo:eliminar' x.id %}">
          <img src="{% static 'trash3.svg' %}" alt="caixote do lixo">
        </a>
        <a href="{% url 'toDo:alterar' x.id %}">
          <img src="{% static 'pencil-fill.svg' %}" alt="lápis">
        </a>
    </li>
    {% endfor %}
</ul>
 
<br>
<a href="{% url 'toDo:inserir' %}">Adicionar tarefa</a>
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="green" class="bi bi-plus-circle" viewBox="0 0 16 16">
  <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"/>
  <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4"/>
</svg>
</body>
</html>